version: '3.3'
services:
  somethingelse:
    image: klimachallengefs22:heatwaves
    container_name: 'Python'
    restart: always
    networks:
      node_net:
        ipv4_address: 172.28.1.5
  db:
    # Official Postgres image from DockerHub (we use the last version)
      image: 'postgis/postgis:latest'
      container_name: 'postgres'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
      ports:
        - 5432:5432
      expose:
        - '5432'
      environment:
        POSTGRES_USER: root # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: orDtiURVtHUHwiQDeRCv # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: klimachallengefs22 # The PostgreSQL default database (automatically created at first launch)
      volumes:
          - "./SQL/1_DatabaseScript.sql:/docker-entrypoint-initdb.d/init.sql"
      networks:
        node_net:
          ipv4_address: 172.28.1.4

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
# Names our volume
volumes:
    my-db: 
